title: "Hendra's Webite"
tagline: A place to introduce myself to the world!

author:
  name: Hendra Manudinata
  url: https://github.com/hendramanudinata03

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3

tags_path: /tags/
categories_path: /categories/
